# Generated by Django 5.2.15 on 2026-06-23 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['grade', 'last_name', 'first_name'], 'verbose_name': 'دانش\u200cآموز', 'verbose_name_plural': 'دانش\u200cآموزان'},
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='کلاس'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_job',
            field=models.CharField(blank=True, max_length=100, verbose_name='شغل پدر'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_job',
            field=models.CharField(blank=True, max_length=100, verbose_name='شغل مادر'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='والدین (کاربر)'),
        ),
    ]
