# Generated by Django 5.2.15 on 2026-06-25 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_options_student_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', 'ریاضی'), ('physics', 'فیزیک'), ('chemistry', 'شیمی'), ('biology', 'زیست\u200cشناسی'), ('literature', 'ادبیات فارسی'), ('arabic', 'عربی'), ('english', 'انگلیسی'), ('quran', 'قرآن'), ('religious', 'دینی'), ('history', 'تاریخ'), ('geography', 'جغرافیا'), ('social', 'اجتماعی'), ('sports', 'ورزش'), ('art', 'هنر'), ('computer', 'کامپیوتر')], max_length=20, verbose_name='درس')),
                ('exam_type', models.CharField(choices=[('midterm', 'میان\u200cترم'), ('final', 'پایان\u200cترم'), ('quiz', 'آزمون'), ('project', 'پروژه')], max_length=20, verbose_name='نوع آزمون')),
                ('score', models.FloatField(verbose_name='نمره')),
                ('date', models.DateField(verbose_name='تاریخ آزمون')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
            options={
                'verbose_name': 'نمره',
                'verbose_name_plural': 'نمرات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'تأخیر'), ('sick', 'مریضی')], max_length=10, verbose_name='وضعیت')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
            options={
                'verbose_name': 'حضور و غیاب',
                'verbose_name_plural': 'حضور و غیاب',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
