# Generated by Django 5.2.15 on 2026-07-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_grade_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سند')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='فایل')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'اسناد',
                'ordering': ['-created_at'],
            },
        ),
    ]
